baseURL = "https://example.com"
title = "Notepadium"
theme = "hugo-notepadium"
copyright = "Â©2019 Notepadium."

languageCode = "zh-cn"
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
# disqusShortname = "XXX"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
logo = ""
slogan = "100% JavaScript-free"
license = "This work is licensed under a Creative Commons Attribution 4.0 International License."

[params.MathJax]
url = ""  # builtin: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github-gist"
webFonts = true  # builtin: 'Source Code Pro'

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Hugo"
url = "https://gohugo.io/"